### ISSUE TITLE
Having trouble scraping tweets

### ISSUE THREAD

**Issue by 503dannyk** [gutfeeling/twitass#2]
Right now I'm trying to use twitass using your code example: 
from twitass.scraper import AdvancedSearchScraper
ass = AdvancedSearchScraper("python%20since%3A2017-03-01%20until%3A2017-03-02")
tweets = ass.scrape()
print(tweets)

And it is printing an empty list. I installed beautifulsoup4-4.5.3, is 4.5.0 needed? Why do I need to create a virtual environment? Does it only work with python3? I have python3.5.2 via anaconda.

**Comment by Hydrochoeris** [comment]
Remove the
`headers = headers`
from 
`response = requests.get("https://twitter.com/search?q=%s" % self.query, params = {"src" : "typd", "f" : "tweets"}, verify = False, headers = headers)`
in scraper.py
reply if this helps or not.

**Comment by gutfeeling** [comment]
Well spotted @Hydrochoeris . The User-Agent string in the headers was obsolete and was causing the issue. I fixed it in 4c7f25c51cad924f11b28d68a3f299df9e7f58b3.
