### ISSUE TITLE
can this scrape restricted tweets?

### ISSUE THREAD

**Issue by DonaldTsang** [gutfeeling/twitass#3]
As referenced in Tweep, the most common no-API tweet scraper(https://github.com/haccer/tweep/issues/14),  
https://twitter.com/a_fellow_white  cannot be scraped using traditional methods,  
the tweep developer claims that a "scrape after login" feature requires selenium.  
Can this be done in twitass?

**Comment by gutfeeling** [comment]
When I tried to access https://twitter.com/a_fellow_white, I got the message "Account suspended", even though I was logged in.

The logic behind this package is simple : if something is visible using the [public Advanced Search page](https://twitter.com/search-advanced?lang=en), then twitass will fetch it. If you come up with another example of a shadowbanned account, then try that endpoint to check whether the tweets can be fetched.

**Comment by DonaldTsang** [comment]
@gutfeeling ttry have a look at https://twitter.com/Susan_Texan or https://twitter.com/DoubleTMisterB  
Those and many others are being put on restricted mode.

**Comment by gutfeeling** [comment]
Please check it yourself. If the tweets you are looking for appears in the public search results, then twitass will be able to access them. Otherwise, it won't be.

**Comment by DonaldTsang** [comment]
@gutfeeling The two links I included in my last post cannot be found in search result EXCEPT when a user is logged-in in the browser

**Comment by gutfeeling** [comment]
In that case, twitass won't be able to access them. It only scrapes the public results.
